# GitHub Sponsors and external funding for OCTALUME.
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [Harery]

# Uncomment any that you actively use:
# patreon: harery
# open_collective: octalume
# ko_fi: harery
# tidelift: pypi/octalume
# liberapay: harery
# issuehunt: Harery
# polar: harery
# buy_me_a_coffee: harery
# custom: ["https://www.harery.com/sponsor"]
