#!/bin/bash
#
# OCTALUME Framework - Project Initialization Script
# Document ID: INIT-001
# Version: 1.0.0
#
# Usage: ./scripts/init-project.sh <project-name>
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Functions
print_header() {
    echo -e "${BLUE}"
    echo "╔════════════════════════════════════════════════════════════╗"
    echo "║         OCTALUME Enterprise Lifecycle Framework            ║"
    echo "║              Project Initialization Script                 ║"
    echo "╚════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ $1${NC}"
}

# Check arguments
if [ -z "$1" ]; then
    print_header
    print_error "Project name is required!"
    echo ""
    echo "Usage: $0 <project-name>"
    echo ""
    echo "Example: $0 my-enterprise-project"
    exit 1
fi

PROJECT_NAME="$1"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

print_header

echo ""
print_info "Initializing project: ${PROJECT_NAME}"
echo ""

# Step 1: Create artifact directories
echo "Step 1: Creating artifact directories..."
ARTIFACT_DIRS=(
    "artifacts/phase_01_initiation"
    "artifacts/phase_02_requirements"
    "artifacts/phase_03_architecture"
    "artifacts/phase_04_planning"
    "artifacts/phase_05_development"
    "artifacts/phase_06_quality"
    "artifacts/phase_07_deployment"
    "artifacts/phase_08_operations"
)

for dir in "${ARTIFACT_DIRS[@]}"; do
    mkdir -p "$dir"
    print_success "Created $dir/"
done

# Step 2: Initialize memory.json with timestamps
echo ""
echo "Step 2: Initializing memory bank..."
MEMORY_FILE=".claude/memory/memory.json"
mkdir -p "$(dirname "$MEMORY_FILE")"

cat > "$MEMORY_FILE" << EOF
{
  "version": "1.0.0",
  "project_name": "${PROJECT_NAME}",
  "created_at": "${TIMESTAMP}",
  "updated_at": "${TIMESTAMP}",
  "memory": {
    "decisions": {},
    "progress": {},
    "blockers": {},
    "notes": {}
  },
  "statistics": {
    "total_entries": 0,
    "decisions": 0,
    "progress": 0,
    "blockers": 0,
    "notes": 0
  }
}
EOF
print_success "Initialized $MEMORY_FILE"

# Step 3: Create project manifest
echo ""
echo "Step 3: Creating project manifest..."
MANIFEST_FILE="PROJECT_MANIFEST.md"

cat > "$MANIFEST_FILE" << EOF
# Project Manifest

**Project Name:** ${PROJECT_NAME}
**Framework:** OCTALUME Enterprise Lifecycle Framework v1.0
**Created:** ${TIMESTAMP}

---

## Project Status

| Phase | Status | Start Date | End Date |
|-------|--------|------------|----------|
| Phase 1: Initiation | Not Started | - | - |
| Phase 2: Requirements | Not Started | - | - |
| Phase 3: Architecture | Not Started | - | - |
| Phase 4: Planning | Not Started | - | - |
| Phase 5: Development | Not Started | - | - |
| Phase 6: Quality | Not Started | - | - |
| Phase 7: Deployment | Not Started | - | - |
| Phase 8: Operations | Not Started | - | - |

---

## Quick Links

- [CLAUDE.md](CLAUDE.md) - AI Agent Guidelines
- [SETUP_GUIDE.md](SETUP_GUIDE.md) - Setup Instructions
- [DIRECTORY_STRUCTURE.md](DIRECTORY_STRUCTURE.md) - Project Structure

---

## Team

| Role | Name | Contact |
|------|------|---------|
| Project Manager | TBD | - |
| Technical Lead | TBD | - |
| Product Owner | TBD | - |

---

*Generated by OCTALUME init-project.sh*
EOF
print_success "Created $MANIFEST_FILE"

# Step 4: Create .gitignore if not exists
echo ""
echo "Step 4: Configuring .gitignore..."
GITIGNORE_FILE=".gitignore"

if [ ! -f "$GITIGNORE_FILE" ]; then
    cat > "$GITIGNORE_FILE" << 'EOF'
# OS files
.DS_Store
Thumbs.db

# Logs
*.log
logs/

# IDE
.vscode/
.idea/
*.swp
*.swo

# Dependencies
node_modules/
__pycache__/
*.pyc
.env
.env.local

# Build artifacts
dist/
build/
*.o
*.exe

# Temporary files
tmp/
temp/
*.tmp

# Sensitive data
*.pem
*.key
secrets/
EOF
    print_success "Created $GITIGNORE_FILE"
else
    # Append if exists
    if ! grep -q ".DS_Store" "$GITIGNORE_FILE"; then
        echo -e "\n# OS files\n.DS_Store" >> "$GITIGNORE_FILE"
    fi
    if ! grep -q "*.log" "$GITIGNORE_FILE"; then
        echo -e "\n# Logs\n*.log" >> "$GITIGNORE_FILE"
    fi
    print_warning "$GITIGNORE_FILE exists - updated with missing entries"
fi

# Step 5: Verify framework files
echo ""
echo "Step 5: Verifying framework files..."
REQUIRED_FILES=(
    "CLAUDE.md"
    "README.md"
    "SETUP_GUIDE.md"
    "DIRECTORY_STRUCTURE.md"
)

for file in "${REQUIRED_FILES[@]}"; do
    if [ -f "$file" ]; then
        print_success "Found $file"
    else
        print_warning "Missing $file - please ensure framework files are present"
    fi
done

# Step 6: Create starter documents
echo ""
echo "Step 6: Creating starter documents..."

# Project Charter starter
CHARTER_FILE="artifacts/phase_01_initiation/PROJECT_CHARTER_${PROJECT_NAME}.md"
cat > "$CHARTER_FILE" << EOF
# Project Charter: ${PROJECT_NAME}

**Document ID:** P1-CHARTER-001
**Version:** 0.1 (Draft)
**Date:** ${TIMESTAMP}

---

## 1. Project Overview

### Project Name
${PROJECT_NAME}

### Project Description
[Describe the project purpose and objectives]

### Business Justification
[Explain the business need and expected value]

---

## 2. Objectives

| ID | Objective | Success Criteria |
|----|-----------|------------------|
| O1 | | |
| O2 | | |
| O3 | | |

---

## 3. Scope

### In Scope
- [Item 1]
- [Item 2]

### Out of Scope
- [Item 1]
- [Item 2]

---

## 4. Stakeholders

| Role | Name | Responsibility |
|------|------|----------------|
| Sponsor | | |
| PM | | |
| Tech Lead | | |

---

## 5. Timeline

| Milestone | Target Date |
|-----------|-------------|
| Project Kickoff | |
| Requirements Complete | |
| Development Complete | |
| Go Live | |

---

## 6. Approvals

| Role | Name | Signature | Date |
|------|------|-----------|------|
| Sponsor | | | |
| PM | | | |

---

*Generated by OCTALUME init-project.sh*
EOF
print_success "Created starter Project Charter"

# Summary
echo ""
echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}   Project '${PROJECT_NAME}' initialized successfully!${NC}"
echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Next steps:"
echo "  1. Review and complete the Project Charter"
echo "  2. Configure team members in PROJECT_MANIFEST.md"
echo "  3. Begin Phase 1: Initiation activities"
echo ""
print_info "Run 'cat CLAUDE.md' to see AI agent guidelines"
echo ""
